INSERT INTO COURSES (name, name_english) VALUES
    ('3º de infantil', '3rd course kids'),
    ('4º de infantil', '4th course kids');

INSERT INTO SESSIONS (name, name_english, trimester, seen, course_id) VALUES
    ('Ordinales', 'Ordinals', 1, false, 1),
    ('Ordinales y fracciones', 'Ordinals and fractions', 1, false, 1),
    ('Fracciones y decimales', 'Fractions and decimals', 1, false, 1),
    ('Ordinales, fracciones y decimales', 'Ordinals, fractions and decimals', 1, false, 1),
    ('Ordinales, fracciones, decimales y geometría', 'Ordinals, fractions, decimals and geometry', 1, false, 1),
    ('Geometría y fracciones', 'Geomotry and fractions', 1, false, 1),
    ('Fracciones, decimales y geometría', 'Fractions, decimals and geometry', 1, false, 1),
    ('Números', 'Numbers', 1, false, 1),
    ('Sumas', 'Sums', 1, false, 1),
    ('Restas', 'Subtractions', 1, false, 1),
    ('Multiplicaciones', 'Multiplications', 1, false, 1),
    ('Divisiones', 'Divisions', 1, false, 1),
    ('Ordinales', 'Ordinals', 2, false, 1),
    ('Ordinales y fracciones', 'Ordinals and fractions', 2, false, 1),
    ('Fracciones y decimales', 'Fractions and decimals', 2, false, 1),
    ('Ordinales, fracciones y decimales', 'Ordinals, fractions and decimals', 2, false, 1),
    ('Ordinales, fracciones, decimales y geometría', 'Ordinals, fractions, decimals and geometry', 2, false, 1),
    ('Geometría y fracciones', 'Geomotry and fractions', 2, false, 1),
    ('Fracciones, decimales y geometría', 'Fractions, decimals and geometry', 2, false, 1),
    ('Números', 'Numbers', 2, false, 1),
    ('Sumas', 'Sums', 2, false, 1),
    ('Restas', 'Subtractions', 2, false, 1),
    ('Multiplicaciones', 'Multiplications', 2, false, 1),
    ('Divisiones', 'Divisions', 2, false, 1),
    ('Ordinales', 'Ordinals', 2, false, 1),
    ('Ordinales y fracciones', 'Ordinals and fractions', 3, false, 1),
    ('Fracciones y decimales', 'Fractions and decimals', 3, false, 1),
    ('Ordinales, fracciones y decimales', 'Ordinals, fractions and decimals', 3, false, 1),
    ('Ordinales, fracciones, decimales y geometría', 'Ordinals, fractions, decimals and geometry', 3, false, 1),
    ('Geometría y fracciones', 'Geomotry and fractions', 3, false, 1),
    ('Fracciones, decimales y geometría', 'Fractions, decimals and geometry', 3, false, 1),
    ('Números', 'Numbers', 3, false, 1),
    ('Sumas', 'Sums', 3, false, 1),
    ('Restas', 'Subtractions', 3, false, 1),
    ('Multiplicaciones', 'Multiplications', 3, false, 1),
    ('Divisiones', 'Divisions', 3, false, 1),
    ('Ordinales', 'Ordinals', 1, false, 2),
    ('Ordinales y fracciones', 'Ordinals and fractions', 1, false, 2),
    ('Fracciones y decimales', 'Fractions and decimals', 1, false, 2),
    ('Ordinales, fracciones y decimales', 'Ordinals, fractions and decimals', 1, false, 2),
    ('Ordinales, fracciones, decimales y geometría', 'Ordinals, fractions, decimals and geometry', 1, false, 2),
    ('Geometría y fracciones', 'Geomotry and fractions', 1, false, 2),
    ('Fracciones, decimales y geometría', 'Fractions, decimals and geometry', 1, false, 2),
    ('Números', 'Numbers', 1, false, 2),
    ('Sumas', 'Sums', 1, false, 2),
    ('Restas', 'Subtractions', 1, false, 2),
    ('Multiplicaciones', 'Multiplications', 1, false, 2),
    ('Divisiones', 'Divisions', 1, false, 2),
    ('Ordinales', 'Ordinals', 2, false, 2),
    ('Ordinales y fracciones', 'Ordinals and fractions', 2, false, 2),
    ('Fracciones y decimales', 'Fractions and decimals', 2, false, 2),
    ('Ordinales, fracciones y decimales', 'Ordinals, fractions and decimals', 2, false, 2),
    ('Ordinales, fracciones, decimales y geometría', 'Ordinals, fractions, decimals and geometry', 2, false, 2),
    ('Geometría y fracciones', 'Geomotry and fractions', 2, false, 2),
    ('Fracciones, decimales y geometría', 'Fractions, decimals and geometry', 2, false, 2),
    ('Números', 'Numbers', 2, false, 2),
    ('Sumas', 'Sums', 2, false, 2),
    ('Restas', 'Subtractions', 2, false, 2),
    ('Multiplicaciones', 'Multiplications', 2, false, 2),
    ('Divisiones', 'Divisions', 2, false, 2),
    ('Ordinales', 'Ordinals', 2, false, 2),
    ('Ordinales y fracciones', 'Ordinals and fractions', 3, false, 2),
    ('Fracciones y decimales', 'Fractions and decimals', 3, false, 2),
    ('Ordinales, fracciones y decimales', 'Ordinals, fractions and decimals', 3, false, 2),
    ('Ordinales, fracciones, decimales y geometría', 'Ordinals, fractions, decimals and geometry', 3, false, 2),
    ('Geometría y fracciones', 'Geomotry and fractions', 3, false, 2),
    ('Fracciones, decimales y geometría', 'Fractions, decimals and geometry', 3, false, 2),
    ('Números', 'Numbers', 3, false, 2),
    ('Sumas', 'Sums', 3, false, 2),
    ('Restas', 'Subtractions', 3, false, 2),
    ('Multiplicaciones', 'Multiplications', 3, false, 2),
    ('Divisiones', 'Divisions', 3, false, 2);